### ISSUE TITLE
Alternative metrics storage

### ISSUE THREAD

**Issue by alexec** [argoproj-labs/argo-dataflow#268]
Currently we use the step/status to store metrics about the pipeline. This has some upsides and downsides:

* No new storage mechanisms needed. Very cloud-native.
* Strong schema, so hard to change. Could break schema. 
* No time-series capability. No way to reset if corrupted.
* High throughput for etcd. I change per replica per minute.
* We get changes through the step controller we don't care about (updating total or similar).

It might be better to use another service:

* Metrics service. It is for metrics after all.
* Something else.

Some needs:

* Must be able to support auto-scaling. I.e. we need a way for the controller (or maybe lead replica) to find out how many messages are pending (and were pending last time).
* Would be good to be stateless.

**Comment by whynowy** [comment]
Possible solutions:

**1. Current implementation with enhancements - totally homegrown auto-scaling, 0-N, no external dependency.**

- Code complexity

**2. Write our own Metrics API Server, controller works on 0-1, HPA works on 1-N (users write HPA specs).**

- Only one Metrics API Server is allowed in one cluster, which means if this Metrics API Server is installed, ppl can not use other softwares like KEDA in the same cluster.

- User write the HPA specs, so that it could work with the Metrics API Server for auto-scaling (1-N).


- User should also be able to choose not to install our Metrics API Server, but install KEDA and use it to achieve auto-scaling (need to disable our controller 0-1 auto scaling as KEDA already has it).


- This is partially re-building KEDA, the difference is whether to auto-generate HPA objects.


**3. Write our own metrics api server, controller works on 0-1, HPA works on 1-N, HPA objects auto generated based on Pipeline/Step specs**

- Same as (2), only one metrics api server is allowed in one cluster


- User lose the flexibility like (2).


- This is like re-building KEDA .


**4. Leverage KEDA directly, we don’t provide Metrics API Server, our controller does not provide any auto scaling logic (no 0-1 as well).**

- Code simplicity.


- KEDA provides a Metrics API Server, and auto generates HPA objects.


- User write KEDA ScaledObject instead of HPA to let KEDA do auto-scaling (0-N).


- The mechanism is the same as (3), the only difference is whether to use KEDA, or we write our own.


---

Ed Lee:

- I’m currently leaning toward approach 1. I think our autoscaling reqs may be somewhat different from most other apps.
- On the other hand, if we need users to be able to customize the scaling policy, perhaps 4 may be good

Alex Collins:

- People will want to run multiple metrics servers

Derek Wang:

- Prefer either (1) or (4) - either we do everything but differentiate from others, or we do nothing but use existing 3rd party softwares.

**Conclusion:**

1. We will stick with solution (1).
2. We will access metrics endpoints directly to grab data instead of checking status information.
3. Further more, we will eliminate/reduce status update from pods to avoid causing issues for k8s api server.
