### ISSUE TITLE
What's the point of argo dataflow

### ISSUE THREAD

**Issue by boniek83** [argoproj-labs/argo-dataflow#292]
I have trouble understanding what's the point of dataflow is. Why not just use argo events+ argo workflows + couler? Is it replacement for couler that uses workflows and events underneath? Is it something more?

**Comment by alexec** [comment]
https://github.com/argoproj-labs/argo-dataflow/blob/main/docs/DATAFLOW_VS_X.md

**Comment by boniek83** [comment]
Oh so this is basically stream processing. So, why I should choose Dataflow instead of Storm/Flink/Samza/Spark Streaming etc?

**Comment by alexec** [comment]
Very easy to get started. Kubernetes-native. Interop with existing K8S tools.

**Comment by boniek83** [comment]
Thanks for an explanation.

**Comment by alexec** [comment]
No problem. I'd be hesitant to call it "stream processing" because I think that suggests some complex features such as windowing that we don't support (at least yet).

If you've more complex use cases that warrant complex tools, e.g. you need windowing, then dataflow is probably not the right tool for you. For the most common 80 or 90% of use cases, or where workflows or events don't fill the bill because they are "work" and "event" rather than "data" orientated, then it could well be a good choice.
